const puppeteer = require('puppeteer');
const path = require('path');
const fs = require('fs');

(async () => {
    // 16:9 1024x576 base image generated by AI earlier
    const bgPath = 'C:\\Users\\unfor\\.gemini\\antigravity-ide\\brain\\50ef3e03-8e76-4fb4-be06-178b55aaf529\\pulse_thumbnail_obama_center_1781613835420.png';
    const bgBase64 = fs.readFileSync(bgPath).toString('base64');
    
    const html = `
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Teko:wght@500;700&family=Montserrat:wght@400;700;900&display=swap');
            body {
                margin: 0;
                padding: 0;
                width: 1024px;
                height: 576px;
                background-image: url('data:image/png;base64,${bgBase64}');
                background-size: cover;
                background-position: center;
                display: flex;
                flex-direction: column;
                justify-content: flex-end;
                align-items: flex-start;
                font-family: 'Teko', sans-serif;
                box-sizing: border-box;
                padding-left: 60px;
                padding-bottom: 30px;
                position: relative;
            }
            .overlay {
                position: absolute;
                top: 0; left: 0; right: 0; bottom: 0;
                background: linear-gradient(90deg, rgba(0,0,0,0.85) 0%, rgba(0,0,0,0.5) 40%, rgba(0,0,0,0) 100%);
            }
            .content {
                position: relative;
                z-index: 10;
                display: flex;
                flex-direction: column;
                align-items: flex-start;
            }
            .axiom {
                font-size: 170px;
                line-height: 0.8;
                font-weight: 700;
                background: linear-gradient(180deg, #E0FFFF 0%, #00FFCC 100%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                margin: 0;
                letter-spacing: 2px;
                filter: drop-shadow(0 0 20px rgba(0,255,200,0.3));
            }
            .daily-pulse {
                font-size: 120px;
                line-height: 0.9;
                font-weight: 700;
                color: #FFFFFF;
                margin: 0;
                letter-spacing: 1px;
                text-shadow: 2px 2px 10px rgba(0,0,0,0.8);
            }
            .date {
                font-family: 'Montserrat', sans-serif;
                font-size: 32px;
                font-weight: 900;
                color: #00FFCC;
                margin-top: 5px;
                text-transform: uppercase;
                letter-spacing: 4px;
                text-shadow: 2px 2px 10px rgba(0,0,0,0.8);
            }
            .line-container {
                display: flex;
                gap: 10px;
                margin-top: 15px;
                margin-bottom: 15px;
            }
            .line-green {
                width: 300px;
                height: 8px;
                background: linear-gradient(90deg, #00FFCC 0%, #88FF00 100%);
            }
            .url {
                font-family: 'Montserrat', sans-serif;
                font-size: 26px;
                font-weight: 400;
                color: #FFFFFF;
                margin: 0;
                letter-spacing: 1px;
            }
        </style>
    </head>
    <body>
        <div class="overlay"></div>
        <div class="content">
            <div class="axiom">AXIOM</div>
            <div class="daily-pulse">DAILY PULSE</div>
            <div class="date">JUNE 16, 2026</div>
            <div class="line-container">
                <div class="line-green"></div>
            </div>
            <div class="url">darkwavepulse.com</div>
        </div>
    </body>
    </html>
    `;

    const browser = await puppeteer.launch({ headless: 'new' });
    const page = await browser.newPage();
    await page.setViewport({ width: 1024, height: 576 });
    await page.setContent(html);
    // wait for fonts to load
    await new Promise(resolve => setTimeout(resolve, 3000));
    await page.screenshot({ path: 'D:\\axiom-marketing-videos\\Final_Renders_With_Intro\\thumbnails\\pulse_thumbnail_2026-06-16.png' });
    await browser.close();
    console.log('Thumbnail generated!');
})();
