// Generated by Lume Compiler
import { __lume_ask, __lume_think, __lume_generate, __lume_loadConfig } from "../node_modules/@lume/compiler/src/runtime.js";
const __lume_config = __lume_loadConfig();

async function process_article(rawText, source) {
  let result = (await __lume_ask({ prompt: `You are the Axiom Deterministic News Engine (Lume-V Protocol). Read the following raw news article snippet from ${source}, strip all subjective, emotional, and biased adjectives/framing, and return a pure deterministic extraction of the facts. Raw Text: ${rawText} You must return a JSON object with: coreEvent, category, imageKeyword, processTimeline, biasScore, strippedTerms, deterministicRewrite, author.`, model: "gemini.flash", format: "json", config: __lume_config }));
  return result;
}
export { process_article };
