// Generated by Lume Compiler (Bypassed for OpenAI)
import axios from 'axios';

async function process_article(rawText, source) {
  const prompt = `You are the Axiom Deterministic News Engine. Read the following raw news article snippet from ${source}, strip all subjective, emotional, and biased adjectives/framing, and return a pure deterministic extraction of the facts. Raw Text: ${rawText} You must return a JSON object with: coreEvent, category, imageKeyword, processTimeline, biasScore, strippedTerms, deterministicRewrite, author.`;
  
  try {
    const response = await axios.post('https://api.openai.com/v1/chat/completions', {
      model: 'gpt-4o-mini',
      messages: [{ role: 'user', content: prompt }],
      response_format: { type: 'json_object' }
    }, {
      headers: {
        'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
        'Content-Type': 'application/json'
      }
    });

    return JSON.parse(response.data.choices[0].message.content);
  } catch (error) {
    console.error("OpenAI Error:", error.response?.data || error.message);
    throw error;
  }
}
export { process_article };
