// Generated by Lume Compiler
import { __lume_ask, __lume_think, __lume_generate, __lume_loadConfig } from "@lume/compiler/src/runtime.js";
const __lume_config = __lume_loadConfig();

async function rewrite_article(content) {
  let prompt = ("Remove all bias and spin from this news story. Make it clinical and deterministic. Text: " + content);
  let result = (await __lume_ask({ prompt: prompt, model: null, format: null, config: __lume_config }));
  return result;
}
